# Generated by Django 2.1.5 on 2019-01-13 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inqapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_end',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
