# Generated by Django 2.1.5 on 2019-02-03 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inqapp', '0006_customuser_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mobile',
        ),
    ]
