# Generated by Django 2.1.5 on 2019-02-06 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inqapp', '0008_customuser_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_updated',
        ),
    ]
