# Generated by Django 2.1.5 on 2019-02-06 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inqapp', '0009_remove_customuser_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
